project:
  type: website
  output-dir: docs

website:
  title: "Learning Screenwritingg - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: screenplays.qmd
        text: Screenplays
      - href: notes.qmd
        text: Notes
      - href: audio-video-scripts.qmd
        text: Audio Video Scripts       

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
